# Generated by Django 4.2.4 on 2023-08-15 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_adv_65', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisment',
            table='advertisement',
        ),
    ]
